config/routes.rb
Rails.application.routes.draw do
  resources :listings
  
  root    'listings#index'
end

app/models/listing.rb
class Listing < ActiveRecord::Base
    mount_uploader :image, ImageUploader
    
    validates :name, presence: true
    validates :description, presence: true
    validates :start_bid, presence: true, numericality: true,
              :format => { :with => /\A\d{1,6}(\.\d{0,2})?\z/ }
    
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  before_action :set_listing, only: [:show, :edit, :update, :destroy]

  # GET /listings
  # GET /listings.json
  def index
    @listings = Listing.all
  end

  # GET /listings/1
  # GET /listings/1.json
  def show
  end

  # GET /listings/new
  def new
    @listing = Listing.new
  end

  # GET /listings/1/edit
  def edit
  end

  # POST /listings
  # POST /listings.json
  def create
    @listing = Listing.new(listing_params)

    respond_to do |format|
      if @listing.save
        format.html { redirect_to @listing, notice: 'Listing was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /listings/1
  # PATCH/PUT /listings/1.json
  def update
    respond_to do |format|
      if @listing.update(listing_params)
        format.html { redirect_to @listing, notice: 'Listing was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /listings/1
  # DELETE /listings/1.json
  def destroy
    @listing.destroy
    respond_to do |format|
      format.html { redirect_to listings_url, notice: 'Listing was successfully destroyed.' }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_listing
      @listing = Listing.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def listing_params
      params.require(:listing).permit(:name, :start_bid, :description, :image)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
end

app/helpers/listings_helper.rb
module ListingsHelper
    def auction_start
        start_date = Time.new(2016,1,1)
        return start_date
    end
    
    def get_days(today)
        d1 = auction_start
        d2 = today
        days = (d1-d2)/60/60/24
        return days.to_i
    end
    
    def get_minutes(today)
        d1 = auction_start
        d2 = today
        minutes = (d1-d2)/60/60%24
        return minutes.to_i
    end
end

app/views/layouts/_aside.html.erb
<div class="page_header">
    <h3>Watch List</h3>
</div>
<hr>

<div class="watch_item">

</div>

app/views/layouts/_header.html.erb
<div class="container">
    <h1><%= link_to "Logo", root_path, id: "logo" %></h1>
</div>
<div class="container">
    <ul id="nav">
        <li><%= link_to "Listings", listings_path %></li>
        <li><%= link_to "My Bids", "#" %></li>
        <li><%= link_to "Watch List", "#" %></li>
        <li><%= link_to "My Won Items", "#" %></li>
    </ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Charity Auctions</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
    <p id="notice"><%= notice %></p>
    <%= render 'layouts/header' %>
    <div class="container">
      <div class="charity_banner">
        <div id="placeholder_text">
          Charity Banner
        </div>
        
      </div>
      <div class="watch_list">
        <%= render 'layouts/aside' %>
      </div>
      <div class="main_content">
        <%= yield %>
      </div>
    </div>
</body>
</html>

app/views/listings/_form.html.erb
<%= form_for(@listing) do |f| %>
  <% if @listing.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@listing.errors.count, "error") %> prohibited this listing from being saved:</h2>

      <ul>
      <% @listing.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="col-md-10 col-md-offset-1">
    <div class="row">
      <div class="form-group col-md-4">
        <%= f.label :name, "Listing Name", class: "form-label" %>
        <%= f.text_field :name, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-4">
        <%= f.label :image, "Upload Image", class: "form-label" %>
        <%= f.file_field :image, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-4">
        <%= f.label :start_bid, class: "form-label" %>
        <%= f.text_field :start_bid, class: "form-control" %>
      </div>
    </div>
    <div class="row">
      <div class="form-group col-md-4">
        <%= f.label :description, class: "form-label" %>
        <%= f.text_area :description, class: "form-control" %>
      </div>
    </div>  
    
    <div class="row">
      <div class="actions col-md-4">
        <%= f.submit "Submit", class: "btn btn-primary btn-sm" %>
      </div>
    </div>
  </div>
<% end %>

app/views/listings/edit.html.erb
<div class="page_header">
    <h3>Edit Auction Listing</h3>
</div>
<hr>

<%= render 'form' %>

<%= link_to 'Show', @listing %> |
<%= link_to 'Back', listings_path %>

app/views/listings/index.html.erb
<div class="page_header">
  <h3>Listing Auction Items</h3>
</div>
<div class="create_button">
  <%= link_to 'New Listing', new_listing_path, class: "btn btn-primary btn-xs" %>
</div>
<hr>

<% @listings.each do |listing| %>
  <div class="item_listing">
    <div class="item_thumbnail">
        <%= image_tag listing.image_url(:thumb).to_s %>
    </div>
    <div class="item_attributes">
      <div class="item_head">
        <strong><%= link_to listing.name, listing %></strong>
      </div><br>
        Start Bid: <strong><%= number_to_currency(listing.start_bid, precision: 2) %></strong>
        <div class="time_till">
          Auction starts in <%= get_days(Time.now.utc) %> day(s) and <%= get_minutes(Time.now.utc) %> Hours.
        </div>
    </div>
    <%= link_to "Delete", listing, method: :delete, data: {confirm: "Are you sure?"} %>
    <br>
  </div><br>
  <hr>
<% end %>

<br>

app/views/listings/new.html.erb
<div class="page_header">
    <h3>Create New Auction Listing</h3>
</div>
<hr>

<%= render 'form' %>

<%= link_to 'Back', listings_path %>

app/views/listings/show.html.erb
<div class="page_header">
    <h3><%= @listing.name %></h3>
</div>
<hr>
<div class="show_top">
    <div class="image_display">
        <div id="image_surround">
            <%= image_tag @listing.image_url(:show_image).to_s %>
        </div>
    </div>
    <div class="bid_box">
        <div id="auction_time">
            Time Until Auction: <%= get_days(Time.now.utc) %> Days <%= get_minutes(Time.now.utc) %> Minutes
        </div>
        <div id="current_bid">
            Current Bid: <strong><%= number_to_currency(@listing.start_bid, precision: 2) %></strong>
        </div>
        <div id="bid_fields">
            <div class="surround">
                <div id="bid_text_field">
                    <%= text_field :bid, :place_bid, :disabled => true, class: "form-control" %>
                </div>
                <div id="bid_button">
                    <%= link_to "Place Bid", "#", :disabled => true, class: "btn btn-primary btn-sm", :method => :post %>
                </div>
            </div>
        </div>
        <div id="watch">
            <%= link_to "Add to Watch List", "#" %>
        </div>
    </div>
</div>
<div class="description_box">
    <h3>Description</h3>
    <%= @listing.description %>
</div>

<%= link_to 'Edit', edit_listing_path(@listing) %> |
<%= link_to 'Back', listings_path %>